version: "3"
services:
  app:
    container_name: mpsm-node
    restart: always
    build: .
    ports:
      - 7086:3000
    links:
      - mongo
    networks:
      vpcbr:
        ipv4_address: 10.5.0.5
  mongo:
    container_name: mpsm-mongo
    image: mongo:latest
    command: mongod --port 27018
    environment:
      - MONGO_INITDB_DATABASE=MultiPathStoryMaker
    ports:
      - "27018:27018"
    networks:
      vpcbr:
        ipv4_address: 10.5.0.6
networks:
  vpcbr:
    driver: bridge
    ipam:
      config:
        - subnet: 10.5.0.0/16
          gateway: 10.5.0.1
