version: "3"
services:
  app:
    container_name: mpsm-node
    restart: always
    build: .
    ports:
      - 7086:80
    links:
      - mongo
  mongo:
    container_name: mpsm-mongo
    image: mongo
    ports:
      - "27018:27017"
