version: "3"
services:
  app:
    container_name: mpsm-node
    restart: always
    build: .
    ports:
      - 7086:3000
    links:
      - mongo
  mongo:
    container_name: mpsm-mongo
    image: mongo:latest
    command: mongod --port 27018
    environment:
      - MONGO_INITDB_DATABASE=MultiPathStoryMaker
    ports:
      - "27018:27018"
